argo-cd:
  controller:
    clusterRoleRules:
      enabled: true
      rules:
        - apiGroups:
          - argoproj.io
          resources:
          - applications
          - appprojects
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - list
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - get
          - list
          - watch
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
  applicationSet:
    containerSecurityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
  configs:
    cm:
      url: "https://localhost:8081"
      dex.config: |
        connectors:
        - type: ldap
          id: ldap
          name: LDAP
          config:

            host: ldap-openldap.auth:389
            insecureNoSSL: true
            startTLS: false
        
            bindDN: cn=admin,dc=example,dc=org
            bindPW: admin
    
            usernamePrompt: SSO Username
        
            # User search maps a username and password entered by a user to a LDAP entry.
            userSearch:
              # BaseDN to start the search from. It will translate to the query
              # "(&(objectClass=person)(uid=<username>))".
              baseDN: ou=people,dc=example,dc=org
              # Optional filter to apply when searching the directory.
              filter: "(objectClass=person)"
        
              # username attribute used for comparing user entries. This will be translated
              # and combined with the other filter as "(<attr>=<username>)".
              username: cn
              # The following three fields are direct mappings of attributes on the user entry.
              # String representation of the user.
              idAttr: cn
              # Required. Attribute to map to Email.
              emailAttr: mail
              # Maps to display name of users. No default value.
              nameAttr: cn
              # Maps to preferred username of users. No default value.
              preferredUsernameAttr: cn
        
            # Group search queries for groups given a user entry.
            groupSearch:
              # BaseDN to start the search from. It will translate to the query
              # "(&(objectClass=group)(member=<user uid>))".
              baseDN: ou=groups,dc=example,dc=org
              # Optional filter to apply when searching the directory.
              filter: "(objectClass=groupOfNames)"
        
              # Following list contains field pairs that are used to match a user to a group. It adds an additional
              # requirement to the filter that an attribute in the group must match the user's
              # attribute value.
              userMatchers:
              - userAttr: dn
                groupAttr: member
        
              # Represents group name.
              nameAttr: cn